name: "Delta Lake Connectors Tests"
on: [push, pull_request]
jobs:
  build:
    name: "Run tests "
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        scala: [2.12.8, 2.11.12]
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Run sqlDeltaImport tests
        run: build/sbt "++ ${{ matrix.scala }}" sqlDeltaImport/test
        if: matrix.scala != '2.11.12'
      - name: Run testScalastyle
        run: build/sbt "++ ${{ matrix.scala }}" testScalastyle
      - name: Run standalone and testStandaloneCosmetic tests
        run: build/sbt "++ ${{ matrix.scala }}" standalone/test testStandaloneCosmetic/test
      - name: Run compatibility tests
        run: build/sbt "++ ${{ matrix.scala }}" compatibility/test
        if: matrix.scala != '2.11.12'
      - name: Run flink tests
        run: build/sbt "++ ${{ matrix.scala }}" flinkConnector/test
