name: "Delta Lake Connectors Tests"
on: [push, pull_request]
jobs:
  build:
    name: "Run tests "
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: [2.12.8, 2.11.12]
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache Scala, SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.cache/coursier
          key: delta-sbt-cache-hive23-scala${{ matrix.scala }}
      - name: Run sqlDeltaImport tests
        shell: bash -l {0}
        run: build/sbt "++ ${{ matrix.scala }}" sqlDeltaImport/test compatibility/test
        if: matrix.scala != '2.11.12'
      - name: Run SBT tests
        shell: bash -l {0}
        run: >
          build/sbt "++ ${{ matrix.scala }}" testScalastyle standalone/test
          testStandaloneCosmetic/test hiveMR/test hiveTez/test hive2MR/test
          hive2Tez/test flinkConnector/test